# Site settings
title: Play
email: your_email@example.com
author: TBG
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
